---
# Setup OCP4 DHCP Server on Helper Node

- hosts: all
  vars_files:
    - ../vars/main.yml
  handlers:
  - import_tasks: ../handlers/main.yml

  tasks:
  - name: Install DHCP server package
    dnf:
      name: dhcp-server
      state: latest
  - name: Enable DHCP server daemon
    service:
      name: dhcpd
      enabled: true
      state: stopped
  - name: Enable firewall for DHCP server
    firewalld:
      immediate: true
      permanent: true
      service: dhcp
      state: enabled
  - name: Write out dhcp file
    template:
      src: ../templates/dhcpd.conf.j2
      dest: /etc/dhcp/dhcpd.conf
      backup: true
    notify:
      - restart dhcpd
    when: not uefi
  - name: Write out dhcp file (UEFI)
    template:
      src: ../templates/dhcpd-uefi.conf.j2
      dest: /etc/dhcp/dhcpd.conf
      backup: true
    notify:
      - restart dhcpd
    when: uefi
  
